# Generated by Django 6.0.5 on 2026-05-24 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Description complète')),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('sport', 'Sport'), ('theater', 'Théâtre'), ('festival', 'Festival'), ('conference', 'Conférence'), ('workshop', 'Atelier'), ('comedy', 'Comédie'), ('kids', 'Enfants'), ('other', 'Autre')], default='other', max_length=50)),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='France', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(help_text='Capacité maximale du lieu')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('sales_start_date', models.DateTimeField()),
                ('sales_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évènement',
                'verbose_name_plural': 'Évènements',
                'ordering': ['start_date'],
            },
        ),
    ]
