# Generated by Django 6.0.5 on 2026-05-28 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Description complète')),
                ('category', models.CharField(choices=[('concert', 'Concert'), ('sport', 'Sport'), ('theater', 'Théâtre'), ('festival', 'Festival'), ('conference', 'Conférence'), ('workshop', 'Atelier'), ('comedy', 'Comédie'), ('kids', 'Enfants'), ('other', 'Autre')], default='other', max_length=50)),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='France', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(help_text='Capacité maximale du lieu')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('sales_start_date', models.DateTimeField()),
                ('sales_end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évènement',
                'verbose_name_plural': 'Évènements',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('quantity_available', models.PositiveIntegerField(verbose_name='Quantité disponible')),
                ('max_per_order', models.PositiveIntegerField(default=4, verbose_name='Max par commande')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'verbose_name': 'Type de ticket',
                'verbose_name_plural': 'Types de tickets',
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'start_date'), name='unique_event_title_startdate'),
        ),
    ]
