# Generated by Django 6.0.5 on 2026-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='quantity_initial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='max_per_order',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='quantity_available',
            field=models.PositiveIntegerField(),
        ),
    ]
