# Generated by Django 6.0.5 on 2026-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organisateur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Organisateur', 'Oorganisateur'), ('utilisateur', 'utilisateur'), ('admin', 'administrateur')], default='utilisateur', max_length=20),
        ),
    ]
