# Generated by Django 6.0.5 on 2026-05-16 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_organisateur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adress',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organisateur', 'Organisateur'), ('utilisateur', 'Utilisateur'), ('admin', 'Administrateur')], default='utilisateur', max_length=20),
        ),
    ]
