# Generated by Django 6.0.5 on 2026-05-31 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='guest',
            name='guest_name_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_tickets', to='tickets.order'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('valid', 'Valide'), ('used', 'Utilisé'), ('cancelled', 'Annulé')], default='valid', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='tickets/qrcodes/'),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
